<?php

/**
 * RyaanCMS Domain Pack Knowledge Base
 *
 * Each pack defines the pre-built blueprint for a software category.
 * When AI discovers a user's app type, it maps to one or more of these packs.
 * The MetadataCrudGenerator uses these entity definitions to generate code with ZERO AI cost.
 */
return [

    // ─────────────────────────────────────────────────────────────────────────
    'crm' => [
        'name'             => 'CRM — Customer Relationship Management',
        'icon'             => '🤝',
        'trigger_keywords' => ['crm', 'customer', 'lead', 'deal', 'pipeline', 'sales', 'contact'],
        'entities' => [
            ['name' => 'Lead', 'fields' => [
                ['name' => 'name',   'type' => 'string',  'required' => true,  'label' => 'Full Name'],
                ['name' => 'email',  'type' => 'string',  'required' => false, 'label' => 'Email'],
                ['name' => 'phone',  'type' => 'string',  'required' => false, 'label' => 'Phone'],
                ['name' => 'company','type' => 'string',  'required' => false, 'label' => 'Company'],
                ['name' => 'source', 'type' => 'enum',    'required' => false, 'label' => 'Lead Source',
                 'options' => ['website', 'referral', 'social_media', 'email', 'phone', 'other']],
                ['name' => 'status', 'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['new', 'contacted', 'qualified', 'proposal', 'converted', 'lost']],
                ['name' => 'value',  'type' => 'decimal', 'required' => false, 'label' => 'Deal Value'],
                ['name' => 'notes',  'type' => 'text',    'required' => false, 'label' => 'Notes'],
            ]],
            ['name' => 'Customer', 'fields' => [
                ['name' => 'name',    'type' => 'string', 'required' => true,  'label' => 'Full Name'],
                ['name' => 'email',   'type' => 'string', 'required' => true,  'label' => 'Email'],
                ['name' => 'phone',   'type' => 'string', 'required' => false, 'label' => 'Phone'],
                ['name' => 'company', 'type' => 'string', 'required' => false, 'label' => 'Company'],
                ['name' => 'address', 'type' => 'text',   'required' => false, 'label' => 'Address'],
                ['name' => 'status',  'type' => 'enum',   'required' => true,  'label' => 'Status',
                 'options' => ['active', 'inactive', 'churned']],
            ]],
            ['name' => 'Activity', 'fields' => [
                ['name' => 'title',       'type' => 'string',   'required' => true,  'label' => 'Title'],
                ['name' => 'type',        'type' => 'enum',     'required' => true,  'label' => 'Type',
                 'options' => ['call', 'email', 'meeting', 'task', 'note']],
                ['name' => 'description', 'type' => 'text',     'required' => false, 'label' => 'Description'],
                ['name' => 'due_date',    'type' => 'datetime', 'required' => false, 'label' => 'Due Date'],
                ['name' => 'status',      'type' => 'enum',     'required' => true,  'label' => 'Status',
                 'options' => ['pending', 'completed', 'cancelled']],
            ]],
        ],
        'features' => ['auth', 'dashboard', 'reports', 'notifications', 'tasks', 'search', 'export'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'erp' => [
        'name'             => 'ERP — Enterprise Resource Planning',
        'icon'             => '🏭',
        'trigger_keywords' => ['erp', 'enterprise', 'resource', 'planning', 'manufacturing', 'procurement', 'supply chain'],
        'entities' => [
            ['name' => 'Vendor', 'fields' => [
                ['name' => 'name',       'type' => 'string', 'required' => true,  'label' => 'Vendor Name'],
                ['name' => 'email',      'type' => 'string', 'required' => false, 'label' => 'Email'],
                ['name' => 'phone',      'type' => 'string', 'required' => false, 'label' => 'Phone'],
                ['name' => 'address',    'type' => 'text',   'required' => false, 'label' => 'Address'],
                ['name' => 'tax_number', 'type' => 'string', 'required' => false, 'label' => 'Tax Number'],
                ['name' => 'status',     'type' => 'enum',   'required' => true,  'label' => 'Status',
                 'options' => ['active', 'inactive', 'blacklisted']],
            ]],
            ['name' => 'PurchaseOrder', 'fields' => [
                ['name' => 'po_number',   'type' => 'string',  'required' => true,  'label' => 'PO Number'],
                ['name' => 'order_date',  'type' => 'date',    'required' => true,  'label' => 'Order Date'],
                ['name' => 'total',       'type' => 'decimal', 'required' => true,  'label' => 'Total Amount'],
                ['name' => 'status',      'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['draft', 'sent', 'confirmed', 'received', 'cancelled']],
                ['name' => 'notes',       'type' => 'text',    'required' => false, 'label' => 'Notes'],
            ]],
            ['name' => 'Product', 'fields' => [
                ['name' => 'name',       'type' => 'string',  'required' => true,  'label' => 'Product Name'],
                ['name' => 'sku',        'type' => 'string',  'required' => true,  'label' => 'SKU'],
                ['name' => 'unit',       'type' => 'string',  'required' => true,  'label' => 'Unit'],
                ['name' => 'cost_price', 'type' => 'decimal', 'required' => false, 'label' => 'Cost Price'],
                ['name' => 'sale_price', 'type' => 'decimal', 'required' => false, 'label' => 'Sale Price'],
                ['name' => 'stock',      'type' => 'integer', 'required' => false, 'label' => 'Stock Qty'],
            ]],
        ],
        'features' => ['auth', 'dashboard', 'reports', 'inventory', 'purchase', 'sales', 'accounting', 'notifications'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'ecommerce' => [
        'name'             => 'eCommerce — Online Store',
        'icon'             => '🛍️',
        'trigger_keywords' => ['ecommerce', 'shop', 'store', 'product', 'cart', 'order', 'checkout', 'inventory'],
        'entities' => [
            ['name' => 'Product', 'fields' => [
                ['name' => 'name',        'type' => 'string',  'required' => true,  'label' => 'Product Name'],
                ['name' => 'slug',        'type' => 'string',  'required' => true,  'label' => 'Slug'],
                ['name' => 'description', 'type' => 'text',    'required' => false, 'label' => 'Description'],
                ['name' => 'price',       'type' => 'decimal', 'required' => true,  'label' => 'Price'],
                ['name' => 'sale_price',  'type' => 'decimal', 'required' => false, 'label' => 'Sale Price'],
                ['name' => 'stock',       'type' => 'integer', 'required' => false, 'label' => 'Stock'],
                ['name' => 'sku',         'type' => 'string',  'required' => false, 'label' => 'SKU'],
                ['name' => 'status',      'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['active', 'draft', 'archived']],
            ]],
            ['name' => 'Order', 'fields' => [
                ['name' => 'order_number',    'type' => 'string',  'required' => true,  'label' => 'Order #'],
                ['name' => 'customer_name',   'type' => 'string',  'required' => true,  'label' => 'Customer Name'],
                ['name' => 'customer_email',  'type' => 'string',  'required' => true,  'label' => 'Email'],
                ['name' => 'subtotal',        'type' => 'decimal', 'required' => true,  'label' => 'Subtotal'],
                ['name' => 'tax',             'type' => 'decimal', 'required' => false, 'label' => 'Tax'],
                ['name' => 'total',           'type' => 'decimal', 'required' => true,  'label' => 'Total'],
                ['name' => 'status',          'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded']],
                ['name' => 'shipping_address','type' => 'text',    'required' => false, 'label' => 'Shipping Address'],
            ]],
            ['name' => 'Category', 'fields' => [
                ['name' => 'name',        'type' => 'string', 'required' => true,  'label' => 'Category Name'],
                ['name' => 'slug',        'type' => 'string', 'required' => true,  'label' => 'Slug'],
                ['name' => 'description', 'type' => 'text',  'required' => false, 'label' => 'Description'],
                ['name' => 'is_active',   'type' => 'boolean','required' => false, 'label' => 'Active'],
            ]],
            ['name' => 'Coupon', 'fields' => [
                ['name' => 'code',       'type' => 'string',  'required' => true,  'label' => 'Coupon Code'],
                ['name' => 'type',       'type' => 'enum',    'required' => true,  'label' => 'Type',
                 'options' => ['percentage', 'fixed']],
                ['name' => 'value',      'type' => 'decimal', 'required' => true,  'label' => 'Discount Value'],
                ['name' => 'min_order',  'type' => 'decimal', 'required' => false, 'label' => 'Min Order Amount'],
                ['name' => 'expires_at', 'type' => 'date',    'required' => false, 'label' => 'Expiry Date'],
                ['name' => 'is_active',  'type' => 'boolean', 'required' => false, 'label' => 'Active'],
            ]],
        ],
        'features' => ['auth', 'cart', 'payment', 'dashboard', 'reports', 'inventory', 'reviews', 'notifications'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'marketplace' => [
        'name'             => 'Marketplace — Two-Sided Platform',
        'icon'             => '🏪',
        'trigger_keywords' => ['marketplace', 'platform', 'seller', 'buyer', 'vendor', 'two-sided', 'uber for'],
        'entities' => [
            ['name' => 'Vendor', 'fields' => [
                ['name' => 'business_name', 'type' => 'string', 'required' => true,  'label' => 'Business Name'],
                ['name' => 'email',         'type' => 'string', 'required' => true,  'label' => 'Email'],
                ['name' => 'phone',         'type' => 'string', 'required' => false, 'label' => 'Phone'],
                ['name' => 'description',   'type' => 'text',   'required' => false, 'label' => 'Description'],
                ['name' => 'commission_rate','type' => 'decimal','required' => false, 'label' => 'Commission %'],
                ['name' => 'status',        'type' => 'enum',   'required' => true,  'label' => 'Status',
                 'options' => ['pending', 'approved', 'suspended', 'rejected']],
            ]],
            ['name' => 'Listing', 'fields' => [
                ['name' => 'title',       'type' => 'string',  'required' => true,  'label' => 'Title'],
                ['name' => 'description', 'type' => 'text',    'required' => false, 'label' => 'Description'],
                ['name' => 'price',       'type' => 'decimal', 'required' => true,  'label' => 'Price'],
                ['name' => 'category',    'type' => 'string',  'required' => false, 'label' => 'Category'],
                ['name' => 'location',    'type' => 'string',  'required' => false, 'label' => 'Location'],
                ['name' => 'status',      'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['draft', 'active', 'paused', 'sold']],
            ]],
            ['name' => 'Review', 'fields' => [
                ['name' => 'rating',  'type' => 'integer', 'required' => true,  'label' => 'Rating (1-5)'],
                ['name' => 'title',   'type' => 'string',  'required' => false, 'label' => 'Review Title'],
                ['name' => 'body',    'type' => 'text',    'required' => true,  'label' => 'Review'],
                ['name' => 'status',  'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['pending', 'approved', 'rejected']],
            ]],
        ],
        'features' => ['auth', 'payment', 'search', 'reviews', 'notifications', 'dashboard', 'reports', 'messaging'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'hrm' => [
        'name'             => 'HRM — Human Resource Management',
        'icon'             => '👥',
        'trigger_keywords' => ['hrm', 'hr', 'human resource', 'employee', 'payroll', 'attendance', 'leave'],
        'entities' => [
            ['name' => 'Employee', 'fields' => [
                ['name' => 'employee_id',  'type' => 'string',  'required' => true,  'label' => 'Employee ID'],
                ['name' => 'name',         'type' => 'string',  'required' => true,  'label' => 'Full Name'],
                ['name' => 'email',        'type' => 'string',  'required' => true,  'label' => 'Email'],
                ['name' => 'phone',        'type' => 'string',  'required' => false, 'label' => 'Phone'],
                ['name' => 'department',   'type' => 'string',  'required' => false, 'label' => 'Department'],
                ['name' => 'designation',  'type' => 'string',  'required' => false, 'label' => 'Designation'],
                ['name' => 'salary',       'type' => 'decimal', 'required' => false, 'label' => 'Basic Salary'],
                ['name' => 'join_date',    'type' => 'date',    'required' => false, 'label' => 'Join Date'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['active', 'probation', 'on_leave', 'resigned', 'terminated']],
            ]],
            ['name' => 'LeaveRequest', 'fields' => [
                ['name' => 'type',       'type' => 'enum',    'required' => true,  'label' => 'Leave Type',
                 'options' => ['annual', 'sick', 'casual', 'maternity', 'paternity', 'unpaid']],
                ['name' => 'from_date',  'type' => 'date',    'required' => true,  'label' => 'From Date'],
                ['name' => 'to_date',    'type' => 'date',    'required' => true,  'label' => 'To Date'],
                ['name' => 'days',       'type' => 'integer', 'required' => true,  'label' => 'Total Days'],
                ['name' => 'reason',     'type' => 'text',    'required' => true,  'label' => 'Reason'],
                ['name' => 'status',     'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['pending', 'approved', 'rejected', 'cancelled']],
            ]],
            ['name' => 'Attendance', 'fields' => [
                ['name' => 'date',       'type' => 'date',     'required' => true,  'label' => 'Date'],
                ['name' => 'check_in',   'type' => 'datetime', 'required' => false, 'label' => 'Check In'],
                ['name' => 'check_out',  'type' => 'datetime', 'required' => false, 'label' => 'Check Out'],
                ['name' => 'status',     'type' => 'enum',     'required' => true,  'label' => 'Status',
                 'options' => ['present', 'absent', 'late', 'half_day', 'on_leave']],
                ['name' => 'notes',      'type' => 'text',     'required' => false, 'label' => 'Notes'],
            ]],
        ],
        'features' => ['auth', 'dashboard', 'reports', 'payroll', 'notifications', 'export'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'accounting' => [
        'name'             => 'Accounting System',
        'icon'             => '💰',
        'trigger_keywords' => ['accounting', 'invoice', 'payment', 'ledger', 'journal', 'balance sheet', 'profit', 'expense'],
        'entities' => [
            ['name' => 'Account', 'fields' => [
                ['name' => 'code',    'type' => 'string', 'required' => true,  'label' => 'Account Code'],
                ['name' => 'name',    'type' => 'string', 'required' => true,  'label' => 'Account Name'],
                ['name' => 'type',    'type' => 'enum',   'required' => true,  'label' => 'Account Type',
                 'options' => ['asset', 'liability', 'equity', 'income', 'expense']],
                ['name' => 'balance', 'type' => 'decimal','required' => false, 'label' => 'Current Balance'],
                ['name' => 'is_active','type'=> 'boolean','required' => false, 'label' => 'Active'],
            ]],
            ['name' => 'Invoice', 'fields' => [
                ['name' => 'invoice_number', 'type' => 'string',  'required' => true,  'label' => 'Invoice #'],
                ['name' => 'client_name',    'type' => 'string',  'required' => true,  'label' => 'Client Name'],
                ['name' => 'client_email',   'type' => 'string',  'required' => false, 'label' => 'Client Email'],
                ['name' => 'issue_date',     'type' => 'date',    'required' => true,  'label' => 'Issue Date'],
                ['name' => 'due_date',       'type' => 'date',    'required' => true,  'label' => 'Due Date'],
                ['name' => 'subtotal',       'type' => 'decimal', 'required' => true,  'label' => 'Subtotal'],
                ['name' => 'tax',            'type' => 'decimal', 'required' => false, 'label' => 'Tax'],
                ['name' => 'total',          'type' => 'decimal', 'required' => true,  'label' => 'Total'],
                ['name' => 'status',         'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['draft', 'sent', 'partial', 'paid', 'overdue', 'cancelled']],
            ]],
            ['name' => 'Expense', 'fields' => [
                ['name' => 'title',      'type' => 'string',  'required' => true,  'label' => 'Title'],
                ['name' => 'category',   'type' => 'string',  'required' => false, 'label' => 'Category'],
                ['name' => 'amount',     'type' => 'decimal', 'required' => true,  'label' => 'Amount'],
                ['name' => 'date',       'type' => 'date',    'required' => true,  'label' => 'Date'],
                ['name' => 'paid_by',    'type' => 'string',  'required' => false, 'label' => 'Paid By'],
                ['name' => 'receipt',    'type' => 'string',  'required' => false, 'label' => 'Receipt File'],
                ['name' => 'notes',      'type' => 'text',    'required' => false, 'label' => 'Notes'],
                ['name' => 'status',     'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['pending', 'approved', 'rejected', 'reimbursed']],
            ]],
        ],
        'features' => ['auth', 'dashboard', 'reports', 'tax', 'export', 'notifications'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'lms' => [
        'name'             => 'LMS — Learning Management System',
        'icon'             => '📚',
        'trigger_keywords' => ['lms', 'learning', 'course', 'student', 'teacher', 'lesson', 'quiz', 'enrollment', 'education'],
        'entities' => [
            ['name' => 'Course', 'fields' => [
                ['name' => 'title',       'type' => 'string',  'required' => true,  'label' => 'Course Title'],
                ['name' => 'slug',        'type' => 'string',  'required' => true,  'label' => 'Slug'],
                ['name' => 'description', 'type' => 'text',    'required' => false, 'label' => 'Description'],
                ['name' => 'price',       'type' => 'decimal', 'required' => false, 'label' => 'Price'],
                ['name' => 'level',       'type' => 'enum',    'required' => false, 'label' => 'Level',
                 'options' => ['beginner', 'intermediate', 'advanced']],
                ['name' => 'duration',    'type' => 'string',  'required' => false, 'label' => 'Duration'],
                ['name' => 'status',      'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['draft', 'published', 'archived']],
            ]],
            ['name' => 'Lesson', 'fields' => [
                ['name' => 'title',       'type' => 'string',  'required' => true,  'label' => 'Lesson Title'],
                ['name' => 'content',     'type' => 'text',    'required' => false, 'label' => 'Content'],
                ['name' => 'video_url',   'type' => 'string',  'required' => false, 'label' => 'Video URL'],
                ['name' => 'duration',    'type' => 'integer', 'required' => false, 'label' => 'Duration (mins)'],
                ['name' => 'order',       'type' => 'integer', 'required' => false, 'label' => 'Order'],
                ['name' => 'is_free',     'type' => 'boolean', 'required' => false, 'label' => 'Free Preview'],
            ]],
            ['name' => 'Enrollment', 'fields' => [
                ['name' => 'status',      'type' => 'enum',   'required' => true,  'label' => 'Status',
                 'options' => ['active', 'completed', 'expired', 'cancelled']],
                ['name' => 'progress',    'type' => 'integer','required' => false, 'label' => 'Progress %'],
                ['name' => 'enrolled_at', 'type' => 'date',   'required' => false, 'label' => 'Enrolled On'],
                ['name' => 'expires_at',  'type' => 'date',   'required' => false, 'label' => 'Expires On'],
            ]],
        ],
        'features' => ['auth', 'payment', 'dashboard', 'certificates', 'quizzes', 'progress', 'notifications'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'booking' => [
        'name'             => 'Booking System',
        'icon'             => '📅',
        'trigger_keywords' => ['booking', 'appointment', 'reservation', 'schedule', 'slot', 'service', 'availability'],
        'entities' => [
            ['name' => 'Service', 'fields' => [
                ['name' => 'name',        'type' => 'string',  'required' => true,  'label' => 'Service Name'],
                ['name' => 'description', 'type' => 'text',    'required' => false, 'label' => 'Description'],
                ['name' => 'price',       'type' => 'decimal', 'required' => true,  'label' => 'Price'],
                ['name' => 'duration',    'type' => 'integer', 'required' => true,  'label' => 'Duration (mins)'],
                ['name' => 'is_active',   'type' => 'boolean', 'required' => false, 'label' => 'Active'],
            ]],
            ['name' => 'Booking', 'fields' => [
                ['name' => 'booking_number', 'type' => 'string',  'required' => true,  'label' => 'Booking #'],
                ['name' => 'customer_name',  'type' => 'string',  'required' => true,  'label' => 'Customer Name'],
                ['name' => 'customer_email', 'type' => 'string',  'required' => true,  'label' => 'Email'],
                ['name' => 'customer_phone', 'type' => 'string',  'required' => false, 'label' => 'Phone'],
                ['name' => 'booking_date',   'type' => 'date',    'required' => true,  'label' => 'Date'],
                ['name' => 'booking_time',   'type' => 'string',  'required' => true,  'label' => 'Time'],
                ['name' => 'amount',         'type' => 'decimal', 'required' => false, 'label' => 'Amount'],
                ['name' => 'status',         'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['pending', 'confirmed', 'completed', 'cancelled', 'no_show']],
                ['name' => 'notes',          'type' => 'text',    'required' => false, 'label' => 'Notes'],
            ]],
        ],
        'features' => ['auth', 'calendar', 'payment', 'notifications', 'sms', 'reports'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'hospital' => [
        'name'             => 'Hospital / Clinic Management',
        'icon'             => '🏥',
        'trigger_keywords' => ['hospital', 'clinic', 'patient', 'doctor', 'appointment', 'medical', 'prescription', 'health'],
        'entities' => [
            ['name' => 'Patient', 'fields' => [
                ['name' => 'patient_id',  'type' => 'string',  'required' => true,  'label' => 'Patient ID'],
                ['name' => 'name',        'type' => 'string',  'required' => true,  'label' => 'Full Name'],
                ['name' => 'dob',         'type' => 'date',    'required' => false, 'label' => 'Date of Birth'],
                ['name' => 'gender',      'type' => 'enum',    'required' => false, 'label' => 'Gender',
                 'options' => ['male', 'female', 'other']],
                ['name' => 'phone',       'type' => 'string',  'required' => false, 'label' => 'Phone'],
                ['name' => 'email',       'type' => 'string',  'required' => false, 'label' => 'Email'],
                ['name' => 'address',     'type' => 'text',    'required' => false, 'label' => 'Address'],
                ['name' => 'blood_group', 'type' => 'string',  'required' => false, 'label' => 'Blood Group'],
                ['name' => 'status',      'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['active', 'discharged', 'deceased']],
            ]],
            ['name' => 'Appointment', 'fields' => [
                ['name' => 'appointment_no', 'type' => 'string',  'required' => true,  'label' => 'Appointment #'],
                ['name' => 'doctor',         'type' => 'string',  'required' => true,  'label' => 'Doctor'],
                ['name' => 'department',     'type' => 'string',  'required' => false, 'label' => 'Department'],
                ['name' => 'date',           'type' => 'date',    'required' => true,  'label' => 'Date'],
                ['name' => 'time',           'type' => 'string',  'required' => true,  'label' => 'Time'],
                ['name' => 'type',           'type' => 'enum',    'required' => false, 'label' => 'Type',
                 'options' => ['consultation', 'follow_up', 'emergency', 'routine']],
                ['name' => 'status',         'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['scheduled', 'confirmed', 'completed', 'cancelled', 'no_show']],
                ['name' => 'fee',            'type' => 'decimal', 'required' => false, 'label' => 'Consultation Fee'],
                ['name' => 'notes',          'type' => 'text',    'required' => false, 'label' => 'Notes'],
            ]],
        ],
        'features' => ['auth', 'dashboard', 'reports', 'billing', 'notifications', 'search'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'restaurant' => [
        'name'             => 'Restaurant / Food Management',
        'icon'             => '🍽️',
        'trigger_keywords' => ['restaurant', 'food', 'menu', 'kitchen', 'table', 'order', 'waiter', 'delivery', 'recipe'],
        'entities' => [
            ['name' => 'MenuItem', 'fields' => [
                ['name' => 'name',        'type' => 'string',  'required' => true,  'label' => 'Item Name'],
                ['name' => 'description', 'type' => 'text',    'required' => false, 'label' => 'Description'],
                ['name' => 'category',    'type' => 'string',  'required' => false, 'label' => 'Category'],
                ['name' => 'price',       'type' => 'decimal', 'required' => true,  'label' => 'Price'],
                ['name' => 'is_available','type' => 'boolean', 'required' => false, 'label' => 'Available'],
                ['name' => 'is_veg',      'type' => 'boolean', 'required' => false, 'label' => 'Vegetarian'],
            ]],
            ['name' => 'TableOrder', 'fields' => [
                ['name' => 'order_number', 'type' => 'string',  'required' => true,  'label' => 'Order #'],
                ['name' => 'table_number', 'type' => 'string',  'required' => false, 'label' => 'Table #'],
                ['name' => 'total',        'type' => 'decimal', 'required' => true,  'label' => 'Total'],
                ['name' => 'type',         'type' => 'enum',    'required' => true,  'label' => 'Order Type',
                 'options' => ['dine_in', 'takeaway', 'delivery']],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['pending', 'confirmed', 'preparing', 'ready', 'served', 'completed', 'cancelled']],
                ['name' => 'notes',        'type' => 'text',    'required' => false, 'label' => 'Special Notes'],
            ]],
        ],
        'features' => ['auth', 'dashboard', 'reports', 'kitchen_display', 'payment', 'notifications'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'saas' => [
        'name'             => 'SaaS — Software as a Service',
        'icon'             => '☁️',
        'trigger_keywords' => ['saas', 'subscription', 'plan', 'billing', 'tenant', 'multi-tenant', 'workspace'],
        'entities' => [
            ['name' => 'Plan', 'fields' => [
                ['name' => 'name',           'type' => 'string',  'required' => true,  'label' => 'Plan Name'],
                ['name' => 'price_monthly',  'type' => 'decimal', 'required' => true,  'label' => 'Monthly Price'],
                ['name' => 'price_yearly',   'type' => 'decimal', 'required' => false, 'label' => 'Yearly Price'],
                ['name' => 'max_users',      'type' => 'integer', 'required' => false, 'label' => 'Max Users'],
                ['name' => 'features',       'type' => 'json',    'required' => false, 'label' => 'Features List'],
                ['name' => 'is_popular',     'type' => 'boolean', 'required' => false, 'label' => 'Popular'],
                ['name' => 'is_active',      'type' => 'boolean', 'required' => false, 'label' => 'Active'],
            ]],
            ['name' => 'Subscription', 'fields' => [
                ['name' => 'billing_cycle',  'type' => 'enum',    'required' => true,  'label' => 'Billing Cycle',
                 'options' => ['monthly', 'yearly']],
                ['name' => 'started_at',     'type' => 'date',    'required' => true,  'label' => 'Start Date'],
                ['name' => 'expires_at',     'type' => 'date',    'required' => false, 'label' => 'Expiry Date'],
                ['name' => 'amount',         'type' => 'decimal', 'required' => true,  'label' => 'Amount'],
                ['name' => 'status',         'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['trial', 'active', 'past_due', 'cancelled', 'expired']],
                ['name' => 'trial_ends_at',  'type' => 'date',    'required' => false, 'label' => 'Trial End Date'],
            ]],
        ],
        'features' => ['auth', 'subscription', 'payment', 'multi_tenant', 'dashboard', 'reports', 'api', 'notifications'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'school' => [
        'name'             => 'School / Institute Management',
        'icon'             => '🏫',
        'trigger_keywords' => ['school', 'college', 'institute', 'student', 'class', 'teacher', 'exam', 'grade', 'result', 'fee'],
        'entities' => [
            ['name' => 'Student', 'fields' => [
                ['name' => 'student_id',  'type' => 'string', 'required' => true,  'label' => 'Student ID'],
                ['name' => 'name',        'type' => 'string', 'required' => true,  'label' => 'Full Name'],
                ['name' => 'email',       'type' => 'string', 'required' => false, 'label' => 'Email'],
                ['name' => 'phone',       'type' => 'string', 'required' => false, 'label' => 'Phone'],
                ['name' => 'class',       'type' => 'string', 'required' => false, 'label' => 'Class/Grade'],
                ['name' => 'section',     'type' => 'string', 'required' => false, 'label' => 'Section'],
                ['name' => 'roll_number', 'type' => 'string', 'required' => false, 'label' => 'Roll Number'],
                ['name' => 'status',      'type' => 'enum',   'required' => true,  'label' => 'Status',
                 'options' => ['active', 'inactive', 'graduated', 'transferred', 'expelled']],
            ]],
            ['name' => 'FeeCollection', 'fields' => [
                ['name' => 'receipt_no',  'type' => 'string',  'required' => true,  'label' => 'Receipt #'],
                ['name' => 'month',       'type' => 'string',  'required' => false, 'label' => 'Month'],
                ['name' => 'amount',      'type' => 'decimal', 'required' => true,  'label' => 'Amount'],
                ['name' => 'paid_date',   'type' => 'date',    'required' => true,  'label' => 'Paid Date'],
                ['name' => 'method',      'type' => 'enum',    'required' => false, 'label' => 'Payment Method',
                 'options' => ['cash', 'bank_transfer', 'online', 'cheque']],
                ['name' => 'status',      'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['paid', 'partial', 'pending', 'overdue']],
            ]],
        ],
        'features' => ['auth', 'dashboard', 'reports', 'attendance', 'exams', 'notifications'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'inventory' => [
        'name'             => 'Inventory / Warehouse Management',
        'icon'             => '📦',
        'trigger_keywords' => ['inventory', 'warehouse', 'stock', 'goods', 'items', 'tracking', 'barcode'],
        'entities' => [
            ['name' => 'Item', 'fields' => [
                ['name' => 'name',         'type' => 'string',  'required' => true,  'label' => 'Item Name'],
                ['name' => 'sku',          'type' => 'string',  'required' => true,  'label' => 'SKU / Barcode'],
                ['name' => 'category',     'type' => 'string',  'required' => false, 'label' => 'Category'],
                ['name' => 'unit',         'type' => 'string',  'required' => true,  'label' => 'Unit'],
                ['name' => 'cost_price',   'type' => 'decimal', 'required' => false, 'label' => 'Cost Price'],
                ['name' => 'sale_price',   'type' => 'decimal', 'required' => false, 'label' => 'Sale Price'],
                ['name' => 'quantity',     'type' => 'integer', 'required' => false, 'label' => 'Current Stock'],
                ['name' => 'min_stock',    'type' => 'integer', 'required' => false, 'label' => 'Minimum Stock'],
                ['name' => 'location',     'type' => 'string',  'required' => false, 'label' => 'Warehouse Location'],
                ['name' => 'is_active',    'type' => 'boolean', 'required' => false, 'label' => 'Active'],
            ]],
            ['name' => 'StockMovement', 'fields' => [
                ['name' => 'type',         'type' => 'enum',    'required' => true,  'label' => 'Movement Type',
                 'options' => ['in', 'out', 'adjustment', 'return']],
                ['name' => 'quantity',     'type' => 'integer', 'required' => true,  'label' => 'Quantity'],
                ['name' => 'reference',    'type' => 'string',  'required' => false, 'label' => 'Reference #'],
                ['name' => 'date',         'type' => 'date',    'required' => true,  'label' => 'Date'],
                ['name' => 'notes',        'type' => 'text',    'required' => false, 'label' => 'Notes'],
            ]],
        ],
        'features' => ['auth', 'dashboard', 'reports', 'barcode', 'alerts', 'export', 'notifications'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'real_estate' => [
        'name'             => 'Real Estate / Property Management',
        'icon'             => '🏠',
        'trigger_keywords' => ['real estate', 'property', 'house', 'apartment', 'commercial', 'rent', 'lease', 'mortgage', 'realtor', 'agent', 'land'],
        'entities' => [
            ['name' => 'Property', 'fields' => [
                ['name' => 'title',        'type' => 'string',  'required' => true,  'label' => 'Property Title'],
                ['name' => 'type',         'type' => 'enum',    'required' => true,  'label' => 'Type',
                 'options' => ['apartment', 'house', 'villa', 'office', 'shop', 'land', 'warehouse']],
                ['name' => 'purpose',      'type' => 'enum',    'required' => true,  'label' => 'Purpose',
                 'options' => ['sale', 'rent', 'lease']],
                ['name' => 'price',        'type' => 'decimal', 'required' => true,  'label' => 'Price'],
                ['name' => 'area',         'type' => 'decimal', 'required' => false, 'label' => 'Area (sqft)'],
                ['name' => 'bedrooms',     'type' => 'integer', 'required' => false, 'label' => 'Bedrooms'],
                ['name' => 'bathrooms',    'type' => 'integer', 'required' => false, 'label' => 'Bathrooms'],
                ['name' => 'address',      'type' => 'text',    'required' => true,  'label' => 'Address'],
                ['name' => 'city',         'type' => 'string',  'required' => false, 'label' => 'City'],
                ['name' => 'description',  'type' => 'text',    'required' => false, 'label' => 'Description'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['available', 'under_offer', 'sold', 'rented', 'off_market']],
            ]],
            ['name' => 'PropertyInquiry', 'fields' => [
                ['name' => 'name',         'type' => 'string',  'required' => true,  'label' => 'Inquirer Name'],
                ['name' => 'email',        'type' => 'string',  'required' => true,  'label' => 'Email'],
                ['name' => 'phone',        'type' => 'string',  'required' => false, 'label' => 'Phone'],
                ['name' => 'message',      'type' => 'text',    'required' => false, 'label' => 'Message'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['new', 'contacted', 'viewing_scheduled', 'closed']],
            ]],
            ['name' => 'PropertyAgent', 'fields' => [
                ['name' => 'name',         'type' => 'string',  'required' => true,  'label' => 'Agent Name'],
                ['name' => 'email',        'type' => 'string',  'required' => true,  'label' => 'Email'],
                ['name' => 'phone',        'type' => 'string',  'required' => false, 'label' => 'Phone'],
                ['name' => 'license_no',   'type' => 'string',  'required' => false, 'label' => 'License #'],
                ['name' => 'commission',   'type' => 'decimal', 'required' => false, 'label' => 'Commission %'],
                ['name' => 'is_active',    'type' => 'boolean', 'required' => false, 'label' => 'Active'],
            ]],
        ],
        'features' => ['auth', 'dashboard', 'search', 'map', 'reports', 'gallery', 'notifications', 'export'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'hotel_hospitality' => [
        'name'             => 'Hotel / Hospitality Management',
        'icon'             => '🏨',
        'trigger_keywords' => ['hotel', 'motel', 'resort', 'hospitality', 'room', 'accommodation', 'check-in', 'check-out', 'hostel', 'inn', 'guest house'],
        'entities' => [
            ['name' => 'Room', 'fields' => [
                ['name' => 'room_number',  'type' => 'string',  'required' => true,  'label' => 'Room Number'],
                ['name' => 'type',         'type' => 'enum',    'required' => true,  'label' => 'Room Type',
                 'options' => ['single', 'double', 'twin', 'suite', 'deluxe', 'presidential']],
                ['name' => 'floor',        'type' => 'string',  'required' => false, 'label' => 'Floor'],
                ['name' => 'capacity',     'type' => 'integer', 'required' => false, 'label' => 'Capacity'],
                ['name' => 'price_per_night','type'=> 'decimal','required' => true,  'label' => 'Price/Night'],
                ['name' => 'amenities',    'type' => 'json',    'required' => false, 'label' => 'Amenities'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['available', 'occupied', 'housekeeping', 'maintenance', 'out_of_order']],
            ]],
            ['name' => 'Reservation', 'fields' => [
                ['name' => 'reservation_no','type'=> 'string',  'required' => true,  'label' => 'Reservation #'],
                ['name' => 'guest_name',   'type' => 'string',  'required' => true,  'label' => 'Guest Name'],
                ['name' => 'guest_email',  'type' => 'string',  'required' => true,  'label' => 'Email'],
                ['name' => 'guest_phone',  'type' => 'string',  'required' => false, 'label' => 'Phone'],
                ['name' => 'check_in',     'type' => 'date',    'required' => true,  'label' => 'Check-In Date'],
                ['name' => 'check_out',    'type' => 'date',    'required' => true,  'label' => 'Check-Out Date'],
                ['name' => 'nights',       'type' => 'integer', 'required' => false, 'label' => 'Nights'],
                ['name' => 'adults',       'type' => 'integer', 'required' => false, 'label' => 'Adults'],
                ['name' => 'total',        'type' => 'decimal', 'required' => false, 'label' => 'Total Amount'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['pending', 'confirmed', 'checked_in', 'checked_out', 'cancelled', 'no_show']],
            ]],
        ],
        'features' => ['auth', 'dashboard', 'calendar', 'reports', 'billing', 'housekeeping', 'notifications'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'gym_fitness' => [
        'name'             => 'Gym / Fitness Club Management',
        'icon'             => '💪',
        'trigger_keywords' => ['gym', 'fitness', 'workout', 'exercise', 'member', 'sports club', 'personal trainer', 'crossfit', 'yoga'],
        'entities' => [
            ['name' => 'GymMember', 'fields' => [
                ['name' => 'member_id',    'type' => 'string',  'required' => true,  'label' => 'Member ID'],
                ['name' => 'name',         'type' => 'string',  'required' => true,  'label' => 'Full Name'],
                ['name' => 'email',        'type' => 'string',  'required' => false, 'label' => 'Email'],
                ['name' => 'phone',        'type' => 'string',  'required' => false, 'label' => 'Phone'],
                ['name' => 'dob',          'type' => 'date',    'required' => false, 'label' => 'Date of Birth'],
                ['name' => 'gender',       'type' => 'enum',    'required' => false, 'label' => 'Gender',
                 'options' => ['male', 'female', 'other']],
                ['name' => 'goal',         'type' => 'enum',    'required' => false, 'label' => 'Fitness Goal',
                 'options' => ['weight_loss', 'muscle_gain', 'endurance', 'flexibility', 'general_fitness']],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['active', 'expired', 'frozen', 'cancelled']],
            ]],
            ['name' => 'MembershipPlan', 'fields' => [
                ['name' => 'name',         'type' => 'string',  'required' => true,  'label' => 'Plan Name'],
                ['name' => 'duration',     'type' => 'enum',    'required' => true,  'label' => 'Duration',
                 'options' => ['daily', 'weekly', 'monthly', 'quarterly', 'half_yearly', 'yearly']],
                ['name' => 'price',        'type' => 'decimal', 'required' => true,  'label' => 'Price'],
                ['name' => 'features',     'type' => 'json',    'required' => false, 'label' => 'Included Features'],
                ['name' => 'is_active',    'type' => 'boolean', 'required' => false, 'label' => 'Active'],
            ]],
            ['name' => 'GymAttendance', 'fields' => [
                ['name' => 'date',         'type' => 'date',    'required' => true,  'label' => 'Date'],
                ['name' => 'check_in',     'type' => 'datetime','required' => false, 'label' => 'Check-In Time'],
                ['name' => 'check_out',    'type' => 'datetime','required' => false, 'label' => 'Check-Out Time'],
                ['name' => 'notes',        'type' => 'text',    'required' => false, 'label' => 'Notes'],
            ]],
        ],
        'features' => ['auth', 'dashboard', 'reports', 'attendance', 'payments', 'notifications', 'export'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'pharmacy' => [
        'name'             => 'Pharmacy / Medical Store',
        'icon'             => '💊',
        'trigger_keywords' => ['pharmacy', 'medicine', 'drug', 'prescription', 'dispensary', 'chemist', 'drugstore', 'pharmaceutical'],
        'entities' => [
            ['name' => 'Medicine', 'fields' => [
                ['name' => 'name',         'type' => 'string',  'required' => true,  'label' => 'Medicine Name'],
                ['name' => 'generic_name', 'type' => 'string',  'required' => false, 'label' => 'Generic Name'],
                ['name' => 'brand',        'type' => 'string',  'required' => false, 'label' => 'Brand'],
                ['name' => 'category',     'type' => 'enum',    'required' => false, 'label' => 'Category',
                 'options' => ['tablet', 'capsule', 'syrup', 'injection', 'cream', 'drops', 'inhaler', 'other']],
                ['name' => 'unit',         'type' => 'string',  'required' => true,  'label' => 'Unit (strip/bottle)'],
                ['name' => 'purchase_price','type'=> 'decimal', 'required' => false, 'label' => 'Purchase Price'],
                ['name' => 'sale_price',   'type' => 'decimal', 'required' => true,  'label' => 'Sale Price'],
                ['name' => 'stock',        'type' => 'integer', 'required' => false, 'label' => 'Stock Qty'],
                ['name' => 'expiry_date',  'type' => 'date',    'required' => false, 'label' => 'Expiry Date'],
                ['name' => 'requires_prescription','type'=> 'boolean','required'=>false,'label'=>'Prescription Required'],
            ]],
            ['name' => 'MedicineSale', 'fields' => [
                ['name' => 'invoice_no',   'type' => 'string',  'required' => true,  'label' => 'Invoice #'],
                ['name' => 'customer_name','type' => 'string',  'required' => false, 'label' => 'Customer Name'],
                ['name' => 'total',        'type' => 'decimal', 'required' => true,  'label' => 'Total Amount'],
                ['name' => 'discount',     'type' => 'decimal', 'required' => false, 'label' => 'Discount'],
                ['name' => 'paid',         'type' => 'decimal', 'required' => false, 'label' => 'Amount Paid'],
                ['name' => 'date',         'type' => 'date',    'required' => true,  'label' => 'Sale Date'],
                ['name' => 'payment_method','type'=> 'enum',    'required' => false, 'label' => 'Payment Method',
                 'options' => ['cash', 'card', 'mobile_banking']],
            ]],
        ],
        'features' => ['auth', 'dashboard', 'reports', 'expiry_alerts', 'stock_alerts', 'export', 'notifications'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'logistics' => [
        'name'             => 'Logistics / Delivery Management',
        'icon'             => '🚚',
        'trigger_keywords' => ['logistics', 'delivery', 'shipping', 'fleet', 'courier', 'transport', 'supply chain', 'dispatch', 'parcel', 'freight'],
        'entities' => [
            ['name' => 'Shipment', 'fields' => [
                ['name' => 'tracking_no',  'type' => 'string',  'required' => true,  'label' => 'Tracking Number'],
                ['name' => 'sender_name',  'type' => 'string',  'required' => true,  'label' => 'Sender Name'],
                ['name' => 'sender_phone', 'type' => 'string',  'required' => false, 'label' => 'Sender Phone'],
                ['name' => 'receiver_name','type' => 'string',  'required' => true,  'label' => 'Receiver Name'],
                ['name' => 'receiver_phone','type'=> 'string',  'required' => false, 'label' => 'Receiver Phone'],
                ['name' => 'pickup_address','type'=> 'text',    'required' => true,  'label' => 'Pickup Address'],
                ['name' => 'delivery_address','type'=> 'text',  'required' => true,  'label' => 'Delivery Address'],
                ['name' => 'weight',       'type' => 'decimal', 'required' => false, 'label' => 'Weight (kg)'],
                ['name' => 'charge',       'type' => 'decimal', 'required' => false, 'label' => 'Shipping Charge'],
                ['name' => 'cod_amount',   'type' => 'decimal', 'required' => false, 'label' => 'COD Amount'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['pending', 'picked_up', 'in_transit', 'out_for_delivery', 'delivered', 'failed', 'returned']],
            ]],
            ['name' => 'DeliveryAgent', 'fields' => [
                ['name' => 'name',         'type' => 'string',  'required' => true,  'label' => 'Agent Name'],
                ['name' => 'phone',        'type' => 'string',  'required' => true,  'label' => 'Phone'],
                ['name' => 'vehicle_type', 'type' => 'enum',    'required' => false, 'label' => 'Vehicle Type',
                 'options' => ['bike', 'car', 'van', 'truck', 'cycle']],
                ['name' => 'vehicle_no',   'type' => 'string',  'required' => false, 'label' => 'Vehicle Number'],
                ['name' => 'zone',         'type' => 'string',  'required' => false, 'label' => 'Assigned Zone'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['active', 'inactive', 'on_delivery', 'off_duty']],
            ]],
        ],
        'features' => ['auth', 'dashboard', 'tracking', 'reports', 'map', 'notifications', 'sms', 'export'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'legal' => [
        'name'             => 'Law Firm / Legal Case Management',
        'icon'             => '⚖️',
        'trigger_keywords' => ['law firm', 'legal', 'attorney', 'lawyer', 'case management', 'court', 'litigation', 'barrister', 'solicitor'],
        'entities' => [
            ['name' => 'LegalCase', 'fields' => [
                ['name' => 'case_number',  'type' => 'string',  'required' => true,  'label' => 'Case Number'],
                ['name' => 'title',        'type' => 'string',  'required' => true,  'label' => 'Case Title'],
                ['name' => 'type',         'type' => 'enum',    'required' => true,  'label' => 'Case Type',
                 'options' => ['civil', 'criminal', 'family', 'corporate', 'property', 'labour', 'intellectual_property', 'other']],
                ['name' => 'court',        'type' => 'string',  'required' => false, 'label' => 'Court Name'],
                ['name' => 'filing_date',  'type' => 'date',    'required' => false, 'label' => 'Filing Date'],
                ['name' => 'next_hearing', 'type' => 'date',    'required' => false, 'label' => 'Next Hearing'],
                ['name' => 'description',  'type' => 'text',    'required' => false, 'label' => 'Case Description'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['new', 'active', 'pending_hearing', 'adjourned', 'settled', 'closed', 'won', 'lost']],
            ]],
            ['name' => 'LegalClient', 'fields' => [
                ['name' => 'name',         'type' => 'string',  'required' => true,  'label' => 'Client Name'],
                ['name' => 'email',        'type' => 'string',  'required' => false, 'label' => 'Email'],
                ['name' => 'phone',        'type' => 'string',  'required' => false, 'label' => 'Phone'],
                ['name' => 'address',      'type' => 'text',    'required' => false, 'label' => 'Address'],
                ['name' => 'type',         'type' => 'enum',    'required' => false, 'label' => 'Client Type',
                 'options' => ['individual', 'company']],
                ['name' => 'notes',        'type' => 'text',    'required' => false, 'label' => 'Notes'],
            ]],
        ],
        'features' => ['auth', 'dashboard', 'calendar', 'documents', 'billing', 'notifications', 'reports'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'ngo_charity' => [
        'name'             => 'NGO / Charity / Nonprofit',
        'icon'             => '❤️',
        'trigger_keywords' => ['ngo', 'charity', 'nonprofit', 'donation', 'fundraising', 'volunteer', 'foundation', 'social work', 'welfare'],
        'entities' => [
            ['name' => 'Donor', 'fields' => [
                ['name' => 'name',         'type' => 'string',  'required' => true,  'label' => 'Donor Name'],
                ['name' => 'email',        'type' => 'string',  'required' => false, 'label' => 'Email'],
                ['name' => 'phone',        'type' => 'string',  'required' => false, 'label' => 'Phone'],
                ['name' => 'country',      'type' => 'string',  'required' => false, 'label' => 'Country'],
                ['name' => 'type',         'type' => 'enum',    'required' => false, 'label' => 'Donor Type',
                 'options' => ['individual', 'corporate', 'foundation', 'government']],
                ['name' => 'total_donated','type' => 'decimal', 'required' => false, 'label' => 'Total Donated'],
                ['name' => 'notes',        'type' => 'text',    'required' => false, 'label' => 'Notes'],
            ]],
            ['name' => 'Donation', 'fields' => [
                ['name' => 'receipt_no',   'type' => 'string',  'required' => true,  'label' => 'Receipt #'],
                ['name' => 'amount',       'type' => 'decimal', 'required' => true,  'label' => 'Amount'],
                ['name' => 'currency',     'type' => 'string',  'required' => false, 'label' => 'Currency'],
                ['name' => 'date',         'type' => 'date',    'required' => true,  'label' => 'Donation Date'],
                ['name' => 'method',       'type' => 'enum',    'required' => false, 'label' => 'Payment Method',
                 'options' => ['cash', 'bank_transfer', 'online', 'cheque', 'crypto']],
                ['name' => 'campaign',     'type' => 'string',  'required' => false, 'label' => 'Campaign / Fund'],
                ['name' => 'is_recurring', 'type' => 'boolean', 'required' => false, 'label' => 'Recurring'],
                ['name' => 'notes',        'type' => 'text',    'required' => false, 'label' => 'Notes'],
            ]],
            ['name' => 'Program', 'fields' => [
                ['name' => 'name',         'type' => 'string',  'required' => true,  'label' => 'Program Name'],
                ['name' => 'description',  'type' => 'text',    'required' => false, 'label' => 'Description'],
                ['name' => 'budget',       'type' => 'decimal', 'required' => false, 'label' => 'Budget'],
                ['name' => 'start_date',   'type' => 'date',    'required' => false, 'label' => 'Start Date'],
                ['name' => 'end_date',     'type' => 'date',    'required' => false, 'label' => 'End Date'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['planning', 'active', 'completed', 'cancelled']],
            ]],
        ],
        'features' => ['auth', 'dashboard', 'reports', 'payment', 'email', 'certificates', 'export', 'notifications'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'project_management' => [
        'name'             => 'Project Management System',
        'icon'             => '📋',
        'trigger_keywords' => ['project management', 'task management', 'kanban', 'sprint', 'agile', 'scrum', 'milestone', 'pm tool', 'trello', 'jira'],
        'entities' => [
            ['name' => 'ProjectTask', 'fields' => [
                ['name' => 'title',        'type' => 'string',  'required' => true,  'label' => 'Task Title'],
                ['name' => 'description',  'type' => 'text',    'required' => false, 'label' => 'Description'],
                ['name' => 'priority',     'type' => 'enum',    'required' => false, 'label' => 'Priority',
                 'options' => ['critical', 'high', 'medium', 'low']],
                ['name' => 'type',         'type' => 'enum',    'required' => false, 'label' => 'Type',
                 'options' => ['feature', 'bug', 'improvement', 'task', 'story']],
                ['name' => 'due_date',     'type' => 'date',    'required' => false, 'label' => 'Due Date'],
                ['name' => 'estimated_hours','type'=> 'decimal','required' => false, 'label' => 'Estimated Hours'],
                ['name' => 'actual_hours', 'type' => 'decimal', 'required' => false, 'label' => 'Actual Hours'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['backlog', 'todo', 'in_progress', 'review', 'done', 'cancelled']],
            ]],
            ['name' => 'Milestone', 'fields' => [
                ['name' => 'title',        'type' => 'string',  'required' => true,  'label' => 'Milestone Title'],
                ['name' => 'description',  'type' => 'text',    'required' => false, 'label' => 'Description'],
                ['name' => 'due_date',     'type' => 'date',    'required' => true,  'label' => 'Due Date'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['upcoming', 'in_progress', 'completed', 'delayed']],
            ]],
            ['name' => 'TimeLog', 'fields' => [
                ['name' => 'date',         'type' => 'date',    'required' => true,  'label' => 'Date'],
                ['name' => 'hours',        'type' => 'decimal', 'required' => true,  'label' => 'Hours Logged'],
                ['name' => 'description',  'type' => 'text',    'required' => false, 'label' => 'What was done'],
            ]],
        ],
        'features' => ['auth', 'dashboard', 'kanban', 'gantt', 'reports', 'time_tracking', 'notifications', 'export'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'event_management' => [
        'name'             => 'Event Management System',
        'icon'             => '🎪',
        'trigger_keywords' => ['event', 'conference', 'seminar', 'ticket', 'venue', 'speaker', 'exhibition', 'concert', 'wedding', 'festival'],
        'entities' => [
            ['name' => 'Event', 'fields' => [
                ['name' => 'title',        'type' => 'string',  'required' => true,  'label' => 'Event Title'],
                ['name' => 'description',  'type' => 'text',    'required' => false, 'label' => 'Description'],
                ['name' => 'type',         'type' => 'enum',    'required' => false, 'label' => 'Event Type',
                 'options' => ['conference', 'seminar', 'workshop', 'concert', 'exhibition', 'wedding', 'sports', 'other']],
                ['name' => 'start_date',   'type' => 'datetime','required' => true,  'label' => 'Start Date & Time'],
                ['name' => 'end_date',     'type' => 'datetime','required' => false, 'label' => 'End Date & Time'],
                ['name' => 'venue',        'type' => 'string',  'required' => false, 'label' => 'Venue'],
                ['name' => 'capacity',     'type' => 'integer', 'required' => false, 'label' => 'Max Capacity'],
                ['name' => 'ticket_price', 'type' => 'decimal', 'required' => false, 'label' => 'Ticket Price'],
                ['name' => 'is_online',    'type' => 'boolean', 'required' => false, 'label' => 'Online Event'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['draft', 'published', 'sold_out', 'cancelled', 'completed']],
            ]],
            ['name' => 'EventTicket', 'fields' => [
                ['name' => 'ticket_no',    'type' => 'string',  'required' => true,  'label' => 'Ticket #'],
                ['name' => 'holder_name',  'type' => 'string',  'required' => true,  'label' => 'Holder Name'],
                ['name' => 'holder_email', 'type' => 'string',  'required' => true,  'label' => 'Email'],
                ['name' => 'ticket_type',  'type' => 'enum',    'required' => false, 'label' => 'Ticket Type',
                 'options' => ['general', 'vip', 'early_bird', 'group', 'complimentary']],
                ['name' => 'amount',       'type' => 'decimal', 'required' => false, 'label' => 'Amount Paid'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['active', 'used', 'cancelled', 'transferred']],
            ]],
        ],
        'features' => ['auth', 'dashboard', 'payment', 'qr_code', 'reports', 'email', 'notifications', 'export'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'travel_agency' => [
        'name'             => 'Travel Agency / Tourism',
        'icon'             => '✈️',
        'trigger_keywords' => ['travel', 'tour', 'tourism', 'package', 'itinerary', 'visa', 'holiday', 'trip', 'vacation', 'airline', 'travel agency'],
        'entities' => [
            ['name' => 'TourPackage', 'fields' => [
                ['name' => 'title',        'type' => 'string',  'required' => true,  'label' => 'Package Name'],
                ['name' => 'destination',  'type' => 'string',  'required' => true,  'label' => 'Destination'],
                ['name' => 'duration',     'type' => 'string',  'required' => false, 'label' => 'Duration (e.g. 5D/4N)'],
                ['name' => 'description',  'type' => 'text',    'required' => false, 'label' => 'Description'],
                ['name' => 'price_per_person','type'=> 'decimal','required'=> true,  'label' => 'Price/Person'],
                ['name' => 'min_persons',  'type' => 'integer', 'required' => false, 'label' => 'Min Persons'],
                ['name' => 'max_persons',  'type' => 'integer', 'required' => false, 'label' => 'Max Persons'],
                ['name' => 'includes',     'type' => 'json',    'required' => false, 'label' => 'Inclusions'],
                ['name' => 'excludes',     'type' => 'json',    'required' => false, 'label' => 'Exclusions'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['active', 'draft', 'archived']],
            ]],
            ['name' => 'TourBooking', 'fields' => [
                ['name' => 'booking_no',   'type' => 'string',  'required' => true,  'label' => 'Booking #'],
                ['name' => 'traveler_name','type' => 'string',  'required' => true,  'label' => 'Lead Traveler'],
                ['name' => 'email',        'type' => 'string',  'required' => true,  'label' => 'Email'],
                ['name' => 'phone',        'type' => 'string',  'required' => false, 'label' => 'Phone'],
                ['name' => 'persons',      'type' => 'integer', 'required' => true,  'label' => 'No. of Persons'],
                ['name' => 'travel_date',  'type' => 'date',    'required' => true,  'label' => 'Travel Date'],
                ['name' => 'total',        'type' => 'decimal', 'required' => false, 'label' => 'Total Amount'],
                ['name' => 'advance_paid', 'type' => 'decimal', 'required' => false, 'label' => 'Advance Paid'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['pending', 'confirmed', 'completed', 'cancelled', 'refunded']],
            ]],
        ],
        'features' => ['auth', 'dashboard', 'payment', 'reports', 'notifications', 'itinerary', 'export'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'car_rental' => [
        'name'             => 'Car Rental / Vehicle Management',
        'icon'             => '🚗',
        'trigger_keywords' => ['car rental', 'vehicle hire', 'auto rental', 'fleet management', 'rent a car', 'vehicle booking'],
        'entities' => [
            ['name' => 'RentalVehicle', 'fields' => [
                ['name' => 'make',         'type' => 'string',  'required' => true,  'label' => 'Make (Toyota/BMW)'],
                ['name' => 'model',        'type' => 'string',  'required' => true,  'label' => 'Model'],
                ['name' => 'year',         'type' => 'integer', 'required' => false, 'label' => 'Year'],
                ['name' => 'plate_number', 'type' => 'string',  'required' => true,  'label' => 'Plate Number'],
                ['name' => 'type',         'type' => 'enum',    'required' => false, 'label' => 'Vehicle Type',
                 'options' => ['sedan', 'suv', 'hatchback', 'van', 'bus', 'truck', 'luxury', 'electric']],
                ['name' => 'daily_rate',   'type' => 'decimal', 'required' => true,  'label' => 'Daily Rate'],
                ['name' => 'seats',        'type' => 'integer', 'required' => false, 'label' => 'Seats'],
                ['name' => 'fuel_type',    'type' => 'enum',    'required' => false, 'label' => 'Fuel Type',
                 'options' => ['petrol', 'diesel', 'electric', 'hybrid', 'cng']],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['available', 'rented', 'maintenance', 'reserved']],
            ]],
            ['name' => 'CarRental', 'fields' => [
                ['name' => 'rental_no',    'type' => 'string',  'required' => true,  'label' => 'Rental #'],
                ['name' => 'customer_name','type' => 'string',  'required' => true,  'label' => 'Customer Name'],
                ['name' => 'customer_phone','type'=> 'string',  'required' => false, 'label' => 'Phone'],
                ['name' => 'pickup_date',  'type' => 'datetime','required' => true,  'label' => 'Pickup Date & Time'],
                ['name' => 'return_date',  'type' => 'datetime','required' => true,  'label' => 'Return Date & Time'],
                ['name' => 'days',         'type' => 'integer', 'required' => false, 'label' => 'Total Days'],
                ['name' => 'total',        'type' => 'decimal', 'required' => false, 'label' => 'Total Charge'],
                ['name' => 'deposit',      'type' => 'decimal', 'required' => false, 'label' => 'Security Deposit'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['reserved', 'active', 'returned', 'cancelled', 'overdue']],
            ]],
        ],
        'features' => ['auth', 'dashboard', 'calendar', 'payment', 'reports', 'notifications', 'export'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'laundry' => [
        'name'             => 'Laundry / Dry Cleaning Management',
        'icon'             => '👕',
        'trigger_keywords' => ['laundry', 'dry cleaning', 'washing', 'ironing', 'laundromat', 'laundry service', 'dhobighat'],
        'entities' => [
            ['name' => 'LaundryOrder', 'fields' => [
                ['name' => 'order_no',     'type' => 'string',  'required' => true,  'label' => 'Order #'],
                ['name' => 'customer_name','type' => 'string',  'required' => true,  'label' => 'Customer Name'],
                ['name' => 'phone',        'type' => 'string',  'required' => false, 'label' => 'Phone'],
                ['name' => 'pickup_date',  'type' => 'date',    'required' => false, 'label' => 'Pickup Date'],
                ['name' => 'delivery_date','type' => 'date',    'required' => false, 'label' => 'Delivery Date'],
                ['name' => 'total',        'type' => 'decimal', 'required' => true,  'label' => 'Total Amount'],
                ['name' => 'advance',      'type' => 'decimal', 'required' => false, 'label' => 'Advance Paid'],
                ['name' => 'notes',        'type' => 'text',    'required' => false, 'label' => 'Special Instructions'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['received', 'processing', 'ready', 'out_for_delivery', 'delivered', 'cancelled']],
            ]],
            ['name' => 'LaundryItem', 'fields' => [
                ['name' => 'item_name',    'type' => 'string',  'required' => true,  'label' => 'Item (shirt/pant)'],
                ['name' => 'service_type', 'type' => 'enum',    'required' => true,  'label' => 'Service',
                 'options' => ['wash', 'dry_clean', 'iron', 'wash_iron', 'stain_removal', 'alteration']],
                ['name' => 'quantity',     'type' => 'integer', 'required' => true,  'label' => 'Qty'],
                ['name' => 'unit_price',   'type' => 'decimal', 'required' => true,  'label' => 'Unit Price'],
                ['name' => 'subtotal',     'type' => 'decimal', 'required' => false, 'label' => 'Subtotal'],
            ]],
        ],
        'features' => ['auth', 'dashboard', 'reports', 'sms', 'notifications', 'export'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'construction' => [
        'name'             => 'Construction / Site Management',
        'icon'             => '🏗️',
        'trigger_keywords' => ['construction', 'building', 'contractor', 'site', 'civil', 'architecture', 'engineering', 'project site', 'real estate development'],
        'entities' => [
            ['name' => 'ConstructionProject', 'fields' => [
                ['name' => 'name',         'type' => 'string',  'required' => true,  'label' => 'Project Name'],
                ['name' => 'client_name',  'type' => 'string',  'required' => false, 'label' => 'Client Name'],
                ['name' => 'location',     'type' => 'string',  'required' => false, 'label' => 'Site Location'],
                ['name' => 'start_date',   'type' => 'date',    'required' => false, 'label' => 'Start Date'],
                ['name' => 'end_date',     'type' => 'date',    'required' => false, 'label' => 'Expected End Date'],
                ['name' => 'budget',       'type' => 'decimal', 'required' => false, 'label' => 'Total Budget'],
                ['name' => 'spent',        'type' => 'decimal', 'required' => false, 'label' => 'Amount Spent'],
                ['name' => 'progress',     'type' => 'integer', 'required' => false, 'label' => 'Progress %'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['planning', 'active', 'on_hold', 'completed', 'cancelled']],
            ]],
            ['name' => 'WorkOrder', 'fields' => [
                ['name' => 'title',        'type' => 'string',  'required' => true,  'label' => 'Work Order Title'],
                ['name' => 'contractor',   'type' => 'string',  'required' => false, 'label' => 'Contractor'],
                ['name' => 'description',  'type' => 'text',    'required' => false, 'label' => 'Description'],
                ['name' => 'start_date',   'type' => 'date',    'required' => false, 'label' => 'Start Date'],
                ['name' => 'due_date',     'type' => 'date',    'required' => false, 'label' => 'Due Date'],
                ['name' => 'amount',       'type' => 'decimal', 'required' => false, 'label' => 'Amount'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['pending', 'active', 'completed', 'disputed']],
            ]],
        ],
        'features' => ['auth', 'dashboard', 'reports', 'materials', 'attendance', 'notifications', 'export'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'insurance' => [
        'name'             => 'Insurance Management System',
        'icon'             => '🛡️',
        'trigger_keywords' => ['insurance', 'policy', 'claim', 'premium', 'underwriting', 'health insurance', 'life insurance', 'auto insurance', 'insurer'],
        'entities' => [
            ['name' => 'InsurancePolicy', 'fields' => [
                ['name' => 'policy_no',    'type' => 'string',  'required' => true,  'label' => 'Policy Number'],
                ['name' => 'holder_name',  'type' => 'string',  'required' => true,  'label' => 'Policy Holder'],
                ['name' => 'type',         'type' => 'enum',    'required' => true,  'label' => 'Insurance Type',
                 'options' => ['life', 'health', 'auto', 'property', 'travel', 'business', 'other']],
                ['name' => 'premium',      'type' => 'decimal', 'required' => true,  'label' => 'Premium Amount'],
                ['name' => 'frequency',    'type' => 'enum',    'required' => false, 'label' => 'Payment Frequency',
                 'options' => ['monthly', 'quarterly', 'half_yearly', 'yearly']],
                ['name' => 'sum_insured',  'type' => 'decimal', 'required' => false, 'label' => 'Sum Insured'],
                ['name' => 'start_date',   'type' => 'date',    'required' => true,  'label' => 'Policy Start'],
                ['name' => 'end_date',     'type' => 'date',    'required' => true,  'label' => 'Policy End'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['active', 'expired', 'suspended', 'cancelled', 'claimed']],
            ]],
            ['name' => 'InsuranceClaim', 'fields' => [
                ['name' => 'claim_no',     'type' => 'string',  'required' => true,  'label' => 'Claim #'],
                ['name' => 'claim_date',   'type' => 'date',    'required' => true,  'label' => 'Claim Date'],
                ['name' => 'amount',       'type' => 'decimal', 'required' => true,  'label' => 'Claim Amount'],
                ['name' => 'approved_amount','type'=> 'decimal','required' => false, 'label' => 'Approved Amount'],
                ['name' => 'description',  'type' => 'text',    'required' => false, 'label' => 'Description'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['submitted', 'under_review', 'approved', 'rejected', 'paid', 'appealed']],
            ]],
        ],
        'features' => ['auth', 'dashboard', 'reports', 'documents', 'notifications', 'export', 'payments'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'freelance_platform' => [
        'name'             => 'Freelance / Gig Platform',
        'icon'             => '💼',
        'trigger_keywords' => ['freelance', 'gig', 'marketplace', 'upwork', 'fiverr', 'proposal', 'contract', 'freelancer', 'remote work'],
        'entities' => [
            ['name' => 'Gig', 'fields' => [
                ['name' => 'title',        'type' => 'string',  'required' => true,  'label' => 'Gig Title'],
                ['name' => 'description',  'type' => 'text',    'required' => true,  'label' => 'Description'],
                ['name' => 'category',     'type' => 'string',  'required' => false, 'label' => 'Category'],
                ['name' => 'base_price',   'type' => 'decimal', 'required' => true,  'label' => 'Starting Price'],
                ['name' => 'delivery_days','type' => 'integer', 'required' => false, 'label' => 'Delivery Days'],
                ['name' => 'revisions',    'type' => 'integer', 'required' => false, 'label' => 'Revisions Included'],
                ['name' => 'tags',         'type' => 'json',    'required' => false, 'label' => 'Tags'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['active', 'paused', 'denied', 'draft']],
            ]],
            ['name' => 'GigOrder', 'fields' => [
                ['name' => 'order_no',     'type' => 'string',  'required' => true,  'label' => 'Order #'],
                ['name' => 'buyer_message','type' => 'text',    'required' => false, 'label' => 'Buyer Requirements'],
                ['name' => 'price',        'type' => 'decimal', 'required' => true,  'label' => 'Price'],
                ['name' => 'deadline',     'type' => 'date',    'required' => false, 'label' => 'Deadline'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['pending', 'in_progress', 'delivered', 'revision', 'completed', 'cancelled', 'disputed']],
            ]],
            ['name' => 'FreelanceReview', 'fields' => [
                ['name' => 'rating',       'type' => 'integer', 'required' => true,  'label' => 'Rating (1–5)'],
                ['name' => 'review',       'type' => 'text',    'required' => false, 'label' => 'Review'],
                ['name' => 'reviewer_type','type' => 'enum',    'required' => true,  'label' => 'Reviewer',
                 'options' => ['buyer', 'seller']],
            ]],
        ],
        'features' => ['auth', 'payment', 'escrow', 'messaging', 'dashboard', 'reports', 'notifications'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'news_media' => [
        'name'             => 'News / Media / Blog Platform',
        'icon'             => '📰',
        'trigger_keywords' => ['news', 'blog', 'media', 'article', 'journalist', 'publication', 'magazine', 'content management', 'editorial'],
        'entities' => [
            ['name' => 'Article', 'fields' => [
                ['name' => 'title',        'type' => 'string',  'required' => true,  'label' => 'Title'],
                ['name' => 'slug',         'type' => 'string',  'required' => true,  'label' => 'URL Slug'],
                ['name' => 'excerpt',      'type' => 'text',    'required' => false, 'label' => 'Excerpt'],
                ['name' => 'body',         'type' => 'text',    'required' => true,  'label' => 'Body Content'],
                ['name' => 'featured_image','type'=> 'string',  'required' => false, 'label' => 'Featured Image URL'],
                ['name' => 'category',     'type' => 'string',  'required' => false, 'label' => 'Category'],
                ['name' => 'tags',         'type' => 'json',    'required' => false, 'label' => 'Tags'],
                ['name' => 'reading_time', 'type' => 'integer', 'required' => false, 'label' => 'Reading Time (mins)'],
                ['name' => 'views',        'type' => 'integer', 'required' => false, 'label' => 'View Count'],
                ['name' => 'is_featured',  'type' => 'boolean', 'required' => false, 'label' => 'Featured'],
                ['name' => 'published_at', 'type' => 'datetime','required' => false, 'label' => 'Published At'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['draft', 'review', 'published', 'archived']],
            ]],
            ['name' => 'NewsComment', 'fields' => [
                ['name' => 'author_name',  'type' => 'string',  'required' => true,  'label' => 'Author Name'],
                ['name' => 'author_email', 'type' => 'string',  'required' => false, 'label' => 'Email'],
                ['name' => 'body',         'type' => 'text',    'required' => true,  'label' => 'Comment'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['pending', 'approved', 'spam', 'deleted']],
            ]],
        ],
        'features' => ['auth', 'dashboard', 'seo', 'categories', 'tags', 'comments', 'search', 'rss', 'notifications'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'telemedicine' => [
        'name'             => 'Telemedicine / Online Healthcare',
        'icon'             => '💻🏥',
        'trigger_keywords' => ['telemedicine', 'online doctor', 'health consultation', 'telehealth', 'virtual clinic', 'e-health', 'online prescription'],
        'entities' => [
            ['name' => 'DoctorProfile', 'fields' => [
                ['name' => 'name',         'type' => 'string',  'required' => true,  'label' => 'Doctor Name'],
                ['name' => 'email',        'type' => 'string',  'required' => true,  'label' => 'Email'],
                ['name' => 'phone',        'type' => 'string',  'required' => false, 'label' => 'Phone'],
                ['name' => 'specialization','type'=> 'string',  'required' => true,  'label' => 'Specialization'],
                ['name' => 'qualification','type' => 'string',  'required' => false, 'label' => 'Qualification (MBBS)'],
                ['name' => 'experience',   'type' => 'integer', 'required' => false, 'label' => 'Years of Experience'],
                ['name' => 'consultation_fee','type'=> 'decimal','required'=> false, 'label' => 'Consultation Fee'],
                ['name' => 'is_available', 'type' => 'boolean', 'required' => false, 'label' => 'Available Online'],
            ]],
            ['name' => 'Consultation', 'fields' => [
                ['name' => 'consult_no',   'type' => 'string',  'required' => true,  'label' => 'Consultation #'],
                ['name' => 'patient_name', 'type' => 'string',  'required' => true,  'label' => 'Patient Name'],
                ['name' => 'symptoms',     'type' => 'text',    'required' => false, 'label' => 'Symptoms'],
                ['name' => 'scheduled_at', 'type' => 'datetime','required' => true,  'label' => 'Scheduled Time'],
                ['name' => 'duration',     'type' => 'integer', 'required' => false, 'label' => 'Duration (mins)'],
                ['name' => 'meeting_link', 'type' => 'string',  'required' => false, 'label' => 'Meeting Link'],
                ['name' => 'diagnosis',    'type' => 'text',    'required' => false, 'label' => 'Diagnosis'],
                ['name' => 'fee',          'type' => 'decimal', 'required' => false, 'label' => 'Fee'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['scheduled', 'waiting', 'in_progress', 'completed', 'cancelled', 'no_show']],
            ]],
        ],
        'features' => ['auth', 'video_call', 'payment', 'prescription', 'dashboard', 'reports', 'notifications', 'sms'],
    ],

    // ─────────────────────────────────────────────────────────────────────────
    'property_rental' => [
        'name'             => 'Property Rental / Tenant Management',
        'icon'             => '🔑',
        'trigger_keywords' => ['rental', 'tenant', 'landlord', 'property management', 'apartment rental', 'lease', 'rent collection', 'flat rent'],
        'entities' => [
            ['name' => 'RentalProperty', 'fields' => [
                ['name' => 'title',        'type' => 'string',  'required' => true,  'label' => 'Property Title'],
                ['name' => 'type',         'type' => 'enum',    'required' => true,  'label' => 'Type',
                 'options' => ['apartment', 'house', 'room', 'office', 'shop', 'floor']],
                ['name' => 'address',      'type' => 'text',    'required' => true,  'label' => 'Address'],
                ['name' => 'rent',         'type' => 'decimal', 'required' => true,  'label' => 'Monthly Rent'],
                ['name' => 'deposit',      'type' => 'decimal', 'required' => false, 'label' => 'Security Deposit'],
                ['name' => 'bedrooms',     'type' => 'integer', 'required' => false, 'label' => 'Bedrooms'],
                ['name' => 'floor',        'type' => 'string',  'required' => false, 'label' => 'Floor'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['vacant', 'occupied', 'maintenance']],
            ]],
            ['name' => 'TenantLease', 'fields' => [
                ['name' => 'tenant_name',  'type' => 'string',  'required' => true,  'label' => 'Tenant Name'],
                ['name' => 'tenant_phone', 'type' => 'string',  'required' => false, 'label' => 'Phone'],
                ['name' => 'nid',          'type' => 'string',  'required' => false, 'label' => 'NID / Passport No'],
                ['name' => 'lease_start',  'type' => 'date',    'required' => true,  'label' => 'Lease Start'],
                ['name' => 'lease_end',    'type' => 'date',    'required' => false, 'label' => 'Lease End'],
                ['name' => 'monthly_rent', 'type' => 'decimal', 'required' => true,  'label' => 'Monthly Rent'],
                ['name' => 'deposit_paid', 'type' => 'decimal', 'required' => false, 'label' => 'Deposit Paid'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['active', 'expired', 'terminated']],
            ]],
            ['name' => 'RentPayment', 'fields' => [
                ['name' => 'receipt_no',   'type' => 'string',  'required' => true,  'label' => 'Receipt #'],
                ['name' => 'month',        'type' => 'string',  'required' => true,  'label' => 'Month (e.g. June 2025)'],
                ['name' => 'amount',       'type' => 'decimal', 'required' => true,  'label' => 'Amount Paid'],
                ['name' => 'paid_date',    'type' => 'date',    'required' => true,  'label' => 'Payment Date'],
                ['name' => 'method',       'type' => 'enum',    'required' => false, 'label' => 'Method',
                 'options' => ['cash', 'bank_transfer', 'mobile_banking', 'cheque']],
                ['name' => 'late_fee',     'type' => 'decimal', 'required' => false, 'label' => 'Late Fee'],
                ['name' => 'status',       'type' => 'enum',    'required' => true,  'label' => 'Status',
                 'options' => ['paid', 'partial', 'pending', 'overdue']],
            ]],
        ],
        'features' => ['auth', 'dashboard', 'reports', 'notifications', 'sms', 'receipts', 'export'],
    ],

];
